In [2]:
import pandas as pd

In [5]:
a= pd.Series([10,20,30,40], index=["SOHAM", "HRIDIN", "KABIR","RAJVEER"])

In [6]:
print(a)

SOHAM      10
HRIDIN     20
KABIR      30
RAJVEER    40
dtype: int64

In [7]:
data = {
    "name": ["Alice", "Bob", "Charlie", "David", "Eva", "Frank", "Grace", "Hassan", "Isha", "Jack"],
    "age": [25, 30, 35, 28, 22, 40, 27, 33, 29, 31],
    "city": ["Delhi", "Mumbai", "Bangalore", "Hyderabad", "Pune", "Chennai", "Kolkata", "Ahmedabad", "Jaipur", "Lucknow"]
}

In [13]:
 pd.DataFrame(data)

      name  age       city
0    Alice   25      Delhi
1      Bob   30     Mumbai
2  Charlie   35  Bangalore
3    David   28  Hyderabad
4      Eva   22       Pune
5    Frank   40    Chennai
6    Grace   27    Kolkata
7   Hassan   33  Ahmedabad
8     Isha   29     Jaipur
9     Jack   31    Lucknow

In [14]:
df

      name  age       city
0    Alice   25      Delhi
1      Bob   30     Mumbai
2  Charlie   35  Bangalore
3    David   28  Hyderabad
4      Eva   22       Pune
5    Frank   40    Chennai
6    Grace   27    Kolkata
7   Hassan   33  Ahmedabad
8     Isha   29     Jaipur
9     Jack   31    Lucknow

In [11]:
print(df.index)

RangeIndex(start=0, stop=10, step=1)

In [12]:
print(df.columns)

Index(['name', 'age', 'city'], dtype='object')