In [1]:
import pandas as pd

In [2]:
#FROM NUMPY LISTS

In [3]:
data = [
["Alice", 25],
["Bob", 30],
["Charlie", 35]
]

In [10]:
d = pd.DataFrame(data, columns= ["Name", "Age"])

In [11]:
print(d)

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35

In [12]:
#FROM NUMPY ARRAYS

In [13]:
import numpy as np

In [14]:
a= np.array([[1,2], [3,4]])

In [15]:
dz = pd.DataFrame(a, columns= ["A", "B"])

In [16]:
print(dz)

   A  B
0  1  2
1  3  4

In [17]:
#READING FILES IN PANDAS

In [18]:
r = pd.read_excel("Sample.xlsx")

In [19]:
print(r)

      Name  Age       City  Score   Department
0    Alice   25      Delhi     88  Engineering
1      Bob   30     Mumbai     92    Marketing
2  Charlie   35  Bangalore     85      Finance
3    David   28  Hyderabad     90           HR
4      Eva   22       Pune     95  Engineering
5    Frank   40    Chennai     78   Operations
6    Grace   27    Kolkata     89       Design
7   Hassan   33  Ahmedabad     91        Sales
8     Isha   29     Jaipur     87      Support
9     Jack   31    Lucknow     93  Engineering

In [21]:
rs=pd.read_csv("Sample.csv")

In [22]:
print(rs)

      Name  Age       City  Score   Department
0    Alice   25      Delhi     88  Engineering
1      Bob   30     Mumbai     92    Marketing
2  Charlie   35  Bangalore     85      Finance
3    David   28  Hyderabad     90           HR
4      Eva   22       Pune     95  Engineering
5    Frank   40    Chennai     78   Operations
6    Grace   27    Kolkata     89       Design
7   Hassan   33  Ahmedabad     91        Sales
8     Isha   29     Jaipur     87      Support
9     Jack   31    Lucknow     93  Engineering

In [27]:
df = pd.read_json("Sample.json")

In [29]:
print(df)

       Name  Age       City  Score   Department
0     Alice   25      Delhi     88  Engineering
1       Bob   30     Mumbai     92    Marketing
2   Charlie   35  Bangalore     85      Finance
3     David   28  Hyderabad     90           HR
4       Eva   22       Pune     95  Engineering
..      ...  ...        ...    ...          ...
85     Ajay   38    Chennai     81   Operations
86    Seema   26    Kolkata     94           HR
87   Tarika   33  Ahmedabad     86       Design
88   Manish   40     Jaipur     78      Finance
89     Renu   29    Lucknow     93      Support

[90 rows x 5 columns]

In [30]:
df.head()

      Name  Age       City  Score   Department
0    Alice   25      Delhi     88  Engineering
1      Bob   30     Mumbai     92    Marketing
2  Charlie   35  Bangalore     85      Finance
3    David   28  Hyderabad     90           HR
4      Eva   22       Pune     95  Engineering

In [32]:
df.tail()

      Name  Age       City  Score  Department
85    Ajay   38    Chennai     81  Operations
86   Seema   26    Kolkata     94          HR
87  Tarika   33  Ahmedabad     86      Design
88  Manish   40     Jaipur     78     Finance
89    Renu   29    Lucknow     93     Support

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 90 entries, 0 to 89
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        90 non-null     object
 1   Age         90 non-null     int64
 2   City        90 non-null     object
 3   Score       90 non-null     int64
 4   Department  90 non-null     object
dtypes: int64(2), object(3)
memory usage: 3.6+ KB

In [36]:
df.describe()

             Age      Score
count  90.000000  90.000000
mean   31.122222  87.766667
std     5.325005   5.227520
min    22.000000  77.000000
25%    27.000000  84.000000
50%    30.500000  88.500000
75%    35.000000  92.000000
max    41.000000  97.000000

In [38]:
df.columns

Index(['Name', 'Age', 'City', 'Score', 'Department'], dtype='object')

In [39]:
df.shape

(90, 5)