In [1]:
import pandas as pd

In [2]:
df=pd.read_excel("Movie Data.xlsx")

In [3]:
df

                  Name   Highest Grossing Movie  Year  imdb  Collection
0       Hrithik Roshan                      War  2019   6.5         476
1       Shah Rukh Khan                    Jawan  2023   7.0        1160
2          Salman Khan          Tiger Zinda Hai  2017   5.9         565
3           Aamir Khan                   Dangal  2016   8.3        2024
4        Ranbir Kapoor                   Animal  2023   6.2         917
5        Ranveer Singh                Padmaavat  2018   7.0         585
6         Akshay Kumar               Good Newwz  2019   6.8         318
7           Ajay Devgn                  Tanhaji  2020   7.5         367
8         Varun Dhawan                 Judwaa 2  2017   3.7         227
9         Tiger Shroff                      War  2019   6.5         476
10       Kartik Aaryan        Bhool Bhulaiyaa 2  2022   5.7         267
11       Vicky Kaushal  Uri The Surgical Strike  2019   8.2         342
12  Ayushmann Khurrana               Dream Girl  2019   6.9         200
13   Sidharth Malhotra                Shershaah  2021   8.3          70
14       Rajkummar Rao                    Stree  2018   7.5         180

In [4]:
df["Name"]

0         Hrithik Roshan
1         Shah Rukh Khan
2            Salman Khan
3             Aamir Khan
4          Ranbir Kapoor
5          Ranveer Singh
6           Akshay Kumar
7             Ajay Devgn
8           Varun Dhawan
9           Tiger Shroff
10         Kartik Aaryan
11         Vicky Kaushal
12    Ayushmann Khurrana
13     Sidharth Malhotra
14         Rajkummar Rao
Name: Name, dtype: object

In [6]:
df[["Name", "Highest Grossing Movie"]]

                  Name   Highest Grossing Movie
0       Hrithik Roshan                      War
1       Shah Rukh Khan                    Jawan
2          Salman Khan          Tiger Zinda Hai
3           Aamir Khan                   Dangal
4        Ranbir Kapoor                   Animal
5        Ranveer Singh                Padmaavat
6         Akshay Kumar               Good Newwz
7           Ajay Devgn                  Tanhaji
8         Varun Dhawan                 Judwaa 2
9         Tiger Shroff                      War
10       Kartik Aaryan        Bhool Bhulaiyaa 2
11       Vicky Kaushal  Uri The Surgical Strike
12  Ayushmann Khurrana               Dream Girl
13   Sidharth Malhotra                Shershaah
14       Rajkummar Rao                    Stree

In [13]:
df2 = df.rename(index = {0:"A", 1:"B"}).copy()

In [14]:
df2

                  Name   Highest Grossing Movie  Year  imdb  Collection
A       Hrithik Roshan                      War  2019   6.5         476
B       Shah Rukh Khan                    Jawan  2023   7.0        1160
2          Salman Khan          Tiger Zinda Hai  2017   5.9         565
3           Aamir Khan                   Dangal  2016   8.3        2024
4        Ranbir Kapoor                   Animal  2023   6.2         917
5        Ranveer Singh                Padmaavat  2018   7.0         585
6         Akshay Kumar               Good Newwz  2019   6.8         318
7           Ajay Devgn                  Tanhaji  2020   7.5         367
8         Varun Dhawan                 Judwaa 2  2017   3.7         227
9         Tiger Shroff                      War  2019   6.5         476
10       Kartik Aaryan        Bhool Bhulaiyaa 2  2022   5.7         267
11       Vicky Kaushal  Uri The Surgical Strike  2019   8.2         342
12  Ayushmann Khurrana               Dream Girl  2019   6.9         200
13   Sidharth Malhotra                Shershaah  2021   8.3          70
14       Rajkummar Rao                    Stree  2018   7.5         180

In [17]:
df2.iloc[0]

Name                      Hrithik Roshan
Highest Grossing Movie               War
Year                                2019
imdb                                 6.5
Collection                           476
Name: A, dtype: object

In [21]:
df2.loc["A"]

Name                      Hrithik Roshan
Highest Grossing Movie               War
Year                                2019
imdb                                 6.5
Collection                           476
Name: A, dtype: object

In [41]:
df.loc[0:3, ["Name", "Highest Grossing Movie"]] #3 INCLUDED

             Name Highest Grossing Movie
0  Hrithik Roshan                    War
1  Shah Rukh Khan                  Jawan
2     Salman Khan        Tiger Zinda Hai
3      Aamir Khan                 Dangal

In [42]:
df.iloc[0:3, 0:2] #3 NOT INCLUDED !!

             Name Highest Grossing Movie
0  Hrithik Roshan                    War
1  Shah Rukh Khan                  Jawan
2     Salman Khan        Tiger Zinda Hai

In [33]:
df2.loc["A", ["Name"]]

Name    Hrithik Roshan
Name: A, dtype: object

In [37]:
df2.at["A","Name"]

'Hrithik Roshan'

In [39]:
df.iat[0,0]

'Hrithik Roshan'