In [11]:
import pandas as pd

In [12]:
df = pd.read_excel("Movie Data.xlsx")

In [13]:
df

                  Name   Highest Grossing Movie  Year  imdb  Collection
0       Hrithik Roshan                      War  2019   6.5         476
1       Shah Rukh Khan                    Jawan  2023   7.0        1160
2          Salman Khan          Tiger Zinda Hai  2017   5.9         565
3           Aamir Khan                   Dangal  2016   8.3        2024
4        Ranbir Kapoor                   Animal  2023   6.2         917
5        Ranveer Singh                Padmaavat  2018   7.0         585
6         Akshay Kumar               Good Newwz  2019   6.8         318
7           Ajay Devgn                  Tanhaji  2020   7.5         367
8         Varun Dhawan                 Judwaa 2  2017   3.7         227
9         Tiger Shroff                      War  2019   6.5         476
10       Kartik Aaryan        Bhool Bhulaiyaa 2  2022   5.7         267
11       Vicky Kaushal  Uri The Surgical Strike  2019   8.2         342
12  Ayushmann Khurrana               Dream Girl  2019   6.9         200
13   Sidharth Malhotra                Shershaah  2021   8.3          70
14       Rajkummar Rao                    Stree  2018   7.5         180

In [52]:
df2 = df.sort_values("imdb").copy()
#df2 = df.sort_values("imdb", ascending=False).copy()

In [53]:
df2

                  Name   Highest Grossing Movie  Year  imdb  Collection
8         Varun Dhawan                 Judwaa 2  2017   3.7         227
10       Kartik Aaryan        Bhool Bhulaiyaa 2  2022   5.7         267
2          Salman Khan          Tiger Zinda Hai  2017   5.9         565
4        Ranbir Kapoor                   Animal  2023   6.2         917
0       Hrithik Roshan                      War  2019   6.5         476
9         Tiger Shroff                      War  2019   6.5         476
6         Akshay Kumar               Good Newwz  2019   6.8         318
12  Ayushmann Khurrana               Dream Girl  2019   6.9         200
1       Shah Rukh Khan                    Jawan  2023   7.0        1160
5        Ranveer Singh                Padmaavat  2018   7.0         585
7           Ajay Devgn                  Tanhaji  2020   7.5         367
14       Rajkummar Rao                    Stree  2018   7.5         180
11       Vicky Kaushal  Uri The Surgical Strike  2019   8.2         342
3           Aamir Khan                   Dangal  2016   8.3        2024
13   Sidharth Malhotra                Shershaah  2021   8.3          70

In [54]:
df2.reset_index(drop=True, inplace=True)

In [55]:
df2

                  Name   Highest Grossing Movie  Year  imdb  Collection
0         Varun Dhawan                 Judwaa 2  2017   3.7         227
1        Kartik Aaryan        Bhool Bhulaiyaa 2  2022   5.7         267
2          Salman Khan          Tiger Zinda Hai  2017   5.9         565
3        Ranbir Kapoor                   Animal  2023   6.2         917
4       Hrithik Roshan                      War  2019   6.5         476
5         Tiger Shroff                      War  2019   6.5         476
6         Akshay Kumar               Good Newwz  2019   6.8         318
7   Ayushmann Khurrana               Dream Girl  2019   6.9         200
8       Shah Rukh Khan                    Jawan  2023   7.0        1160
9        Ranveer Singh                Padmaavat  2018   7.0         585
10          Ajay Devgn                  Tanhaji  2020   7.5         367
11       Rajkummar Rao                    Stree  2018   7.5         180
12       Vicky Kaushal  Uri The Surgical Strike  2019   8.2         342
13          Aamir Khan                   Dangal  2016   8.3        2024
14   Sidharth Malhotra                Shershaah  2021   8.3          70

In [56]:
df2.sort_index()

                  Name   Highest Grossing Movie  Year  imdb  Collection
0         Varun Dhawan                 Judwaa 2  2017   3.7         227
1        Kartik Aaryan        Bhool Bhulaiyaa 2  2022   5.7         267
2          Salman Khan          Tiger Zinda Hai  2017   5.9         565
3        Ranbir Kapoor                   Animal  2023   6.2         917
4       Hrithik Roshan                      War  2019   6.5         476
5         Tiger Shroff                      War  2019   6.5         476
6         Akshay Kumar               Good Newwz  2019   6.8         318
7   Ayushmann Khurrana               Dream Girl  2019   6.9         200
8       Shah Rukh Khan                    Jawan  2023   7.0        1160
9        Ranveer Singh                Padmaavat  2018   7.0         585
10          Ajay Devgn                  Tanhaji  2020   7.5         367
11       Rajkummar Rao                    Stree  2018   7.5         180
12       Vicky Kaushal  Uri The Surgical Strike  2019   8.2         342
13          Aamir Khan                   Dangal  2016   8.3        2024
14   Sidharth Malhotra                Shershaah  2021   8.3          70

In [57]:
df2

                  Name   Highest Grossing Movie  Year  imdb  Collection
0         Varun Dhawan                 Judwaa 2  2017   3.7         227
1        Kartik Aaryan        Bhool Bhulaiyaa 2  2022   5.7         267
2          Salman Khan          Tiger Zinda Hai  2017   5.9         565
3        Ranbir Kapoor                   Animal  2023   6.2         917
4       Hrithik Roshan                      War  2019   6.5         476
5         Tiger Shroff                      War  2019   6.5         476
6         Akshay Kumar               Good Newwz  2019   6.8         318
7   Ayushmann Khurrana               Dream Girl  2019   6.9         200
8       Shah Rukh Khan                    Jawan  2023   7.0        1160
9        Ranveer Singh                Padmaavat  2018   7.0         585
10          Ajay Devgn                  Tanhaji  2020   7.5         367
11       Rajkummar Rao                    Stree  2018   7.5         180
12       Vicky Kaushal  Uri The Surgical Strike  2019   8.2         342
13          Aamir Khan                   Dangal  2016   8.3        2024
14   Sidharth Malhotra                Shershaah  2021   8.3          70

In [64]:
df2["Rank"] = df2["imdb"].rank(ascending=False, method="dense")

In [65]:
df2

                  Name   Highest Grossing Movie  Year  imdb  Collection  Rank
0         Varun Dhawan                 Judwaa 2  2017   3.7         227  11.0
1        Kartik Aaryan        Bhool Bhulaiyaa 2  2022   5.7         267  10.0
2          Salman Khan          Tiger Zinda Hai  2017   5.9         565   9.0
3        Ranbir Kapoor                   Animal  2023   6.2         917   8.0
4       Hrithik Roshan                      War  2019   6.5         476   7.0
5         Tiger Shroff                      War  2019   6.5         476   7.0
6         Akshay Kumar               Good Newwz  2019   6.8         318   6.0
7   Ayushmann Khurrana               Dream Girl  2019   6.9         200   5.0
8       Shah Rukh Khan                    Jawan  2023   7.0        1160   4.0
9        Ranveer Singh                Padmaavat  2018   7.0         585   4.0
10          Ajay Devgn                  Tanhaji  2020   7.5         367   3.0
11       Rajkummar Rao                    Stree  2018   7.5         180   3.0
12       Vicky Kaushal  Uri The Surgical Strike  2019   8.2         342   2.0
13          Aamir Khan                   Dangal  2016   8.3        2024   1.0
14   Sidharth Malhotra                Shershaah  2021   8.3          70   1.0

In [68]:
df3=df2.rename(columns = {"Name" : "NAAM"})

In [69]:
df3

                  NAAM   Highest Grossing Movie  Year  imdb  Collection  Rank
0         Varun Dhawan                 Judwaa 2  2017   3.7         227  11.0
1        Kartik Aaryan        Bhool Bhulaiyaa 2  2022   5.7         267  10.0
2          Salman Khan          Tiger Zinda Hai  2017   5.9         565   9.0
3        Ranbir Kapoor                   Animal  2023   6.2         917   8.0
4       Hrithik Roshan                      War  2019   6.5         476   7.0
5         Tiger Shroff                      War  2019   6.5         476   7.0
6         Akshay Kumar               Good Newwz  2019   6.8         318   6.0
7   Ayushmann Khurrana               Dream Girl  2019   6.9         200   5.0
8       Shah Rukh Khan                    Jawan  2023   7.0        1160   4.0
9        Ranveer Singh                Padmaavat  2018   7.0         585   4.0
10          Ajay Devgn                  Tanhaji  2020   7.5         367   3.0
11       Rajkummar Rao                    Stree  2018   7.5         180   3.0
12       Vicky Kaushal  Uri The Surgical Strike  2019   8.2         342   2.0
13          Aamir Khan                   Dangal  2016   8.3        2024   1.0
14   Sidharth Malhotra                Shershaah  2021   8.3          70   1.0

In [71]:
df4=df3.rename(index = {0:"row1", 1:"row2"})

In [72]:
df4

,NAAM,Highest Grossing Movie,Year,imdb,Collection,Rank
row1,Varun Dhawan,Judwaa 2,2017,3.7,227,11.0
row2,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,5.7,267,10.0
2,Salman Khan,Tiger Zinda Hai,2017,5.9,565,9.0
3,Ranbir Kapoor,Animal,2023,6.2,917,8.0
4,Hrithik Roshan,War,2019,6.5,476,7.0
5,Tiger Shroff,War,2019,6.5,476,7.0
6,Akshay Kumar,Good Newwz,2019,6.8,318,6.0
7,Ayushmann Khurrana,Dream Girl,2019,6.9,200,5.0
8,Shah Rukh Khan,Jawan,2023,7.0,1160,4.0
9,Ranveer Singh,Padmaavat,2018,7.0,585,4.0
10,Ajay Devgn,Tanhaji,2020,7.5,367,3.0
11,Rajkummar Rao,Stree,2018,7.5,180,3.0
12,Vicky Kaushal,Uri The Surgical Strike,2019,8.2,342,2.0
13,Aamir Khan,Dangal,2016,8.3,2024,1.0
14,Sidharth Malhotra,Shershaah,2021,8.3,70,1.0

In [75]:
df4.columns = ["a","b","c","d","e","f"]

In [76]:
df4

                       a                        b     c    d     e     f
row1        Varun Dhawan                 Judwaa 2  2017  3.7   227  11.0
row2       Kartik Aaryan        Bhool Bhulaiyaa 2  2022  5.7   267  10.0
2            Salman Khan          Tiger Zinda Hai  2017  5.9   565   9.0
3          Ranbir Kapoor                   Animal  2023  6.2   917   8.0
4         Hrithik Roshan                      War  2019  6.5   476   7.0
5           Tiger Shroff                      War  2019  6.5   476   7.0
6           Akshay Kumar               Good Newwz  2019  6.8   318   6.0
7     Ayushmann Khurrana               Dream Girl  2019  6.9   200   5.0
8         Shah Rukh Khan                    Jawan  2023  7.0  1160   4.0
9          Ranveer Singh                Padmaavat  2018  7.0   585   4.0
10            Ajay Devgn                  Tanhaji  2020  7.5   367   3.0
11         Rajkummar Rao                    Stree  2018  7.5   180   3.0
12         Vicky Kaushal  Uri The Surgical Strike  2019  8.2   342   2.0
13            Aamir Khan                   Dangal  2016  8.3  2024   1.0
14     Sidharth Malhotra                Shershaah  2021  8.3    70   1.0

In [79]:
df4 = df4[["e","f","c","d","a","b"]]

In [80]:
df4

         e     f     c    d                   a                        b
row1   227  11.0  2017  3.7        Varun Dhawan                 Judwaa 2
row2   267  10.0  2022  5.7       Kartik Aaryan        Bhool Bhulaiyaa 2
2      565   9.0  2017  5.9         Salman Khan          Tiger Zinda Hai
3      917   8.0  2023  6.2       Ranbir Kapoor                   Animal
4      476   7.0  2019  6.5      Hrithik Roshan                      War
5      476   7.0  2019  6.5        Tiger Shroff                      War
6      318   6.0  2019  6.8        Akshay Kumar               Good Newwz
7      200   5.0  2019  6.9  Ayushmann Khurrana               Dream Girl
8     1160   4.0  2023  7.0      Shah Rukh Khan                    Jawan
9      585   4.0  2018  7.0       Ranveer Singh                Padmaavat
10     367   3.0  2020  7.5          Ajay Devgn                  Tanhaji
11     180   3.0  2018  7.5       Rajkummar Rao                    Stree
12     342   2.0  2019  8.2       Vicky Kaushal  Uri The Surgical Strike
13    2024   1.0  2016  8.3          Aamir Khan                   Dangal
14      70   1.0  2021  8.3   Sidharth Malhotra                Shershaah