In [2]:
import pandas as pd

In [4]:
data = {
    'Movie': ['Interstellar', 'Joker', 'Avengers Endgame', 'Parasite'],
    'Director': ['Nolan', 'Todd Phillips', 'Russo Brothers', 'Bong Joon-ho'],
    'Year': [2014, 2019, 2019, 2019],
    'Budget': [165, 70, 356, 11],
    'BoxOffice': [701, 1074, 2798, 262],
    'imdb': [8.6, 8.4, 8.4, 8.5]
}

df = pd.DataFrame(data)

print(df)

              Movie        Director  Year  Budget  BoxOffice  imdb
0      Interstellar           Nolan  2014     165        701   8.6
1             Joker   Todd Phillips  2019      70       1074   8.4
2  Avengers Endgame  Russo Brothers  2019     356       2798   8.4
3          Parasite    Bong Joon-ho  2019      11        262   8.5

In [5]:
df.melt(id_vars=["Movie"], value_vars=["Director", "Year", "Budget", "BoxOffice", "imdb"], var_name="Aspects", value_name="Data")

               Movie    Aspects            Data
0       Interstellar   Director           Nolan
1              Joker   Director   Todd Phillips
2   Avengers Endgame   Director  Russo Brothers
3           Parasite   Director    Bong Joon-ho
4       Interstellar       Year            2014
5              Joker       Year            2019
6   Avengers Endgame       Year            2019
7           Parasite       Year            2019
8       Interstellar     Budget             165
9              Joker     Budget              70
10  Avengers Endgame     Budget             356
11          Parasite     Budget              11
12      Interstellar  BoxOffice             701
13             Joker  BoxOffice            1074
14  Avengers Endgame  BoxOffice            2798
15          Parasite  BoxOffice             262
16      Interstellar       imdb             8.6
17             Joker       imdb             8.4
18  Avengers Endgame       imdb             8.4
19          Parasite       imdb             8.5

In [8]:
df2=df.melt(
    id_vars=["Movie", "Director", "Year"],
    value_vars=["Budget", "BoxOffice", "imdb"],
    var_name="Metric",
    value_name="Value"
)

In [9]:
df2

               Movie        Director  Year     Metric   Value
0       Interstellar           Nolan  2014     Budget   165.0
1              Joker   Todd Phillips  2019     Budget    70.0
2   Avengers Endgame  Russo Brothers  2019     Budget   356.0
3           Parasite    Bong Joon-ho  2019     Budget    11.0
4       Interstellar           Nolan  2014  BoxOffice   701.0
5              Joker   Todd Phillips  2019  BoxOffice  1074.0
6   Avengers Endgame  Russo Brothers  2019  BoxOffice  2798.0
7           Parasite    Bong Joon-ho  2019  BoxOffice   262.0
8       Interstellar           Nolan  2014       imdb     8.6
9              Joker   Todd Phillips  2019       imdb     8.4
10  Avengers Endgame  Russo Brothers  2019       imdb     8.4
11          Parasite    Bong Joon-ho  2019       imdb     8.5

In [7]:
#PIVOT

In [13]:
df3 = df2.pivot(
    index=["Movie", "Director", "Year"],
    columns="Metric",
    values="Value"
).reset_index()

In [14]:
df3

Metric             Movie        Director  Year  BoxOffice  Budget  imdb
0       Avengers Endgame  Russo Brothers  2019     2798.0   356.0   8.4
1           Interstellar           Nolan  2014      701.0   165.0   8.6
2                  Joker   Todd Phillips  2019     1074.0    70.0   8.4
3               Parasite    Bong Joon-ho  2019      262.0    11.0   8.5

In [15]:
#AGGREGATIONS!!

In [6]:
df = pd.DataFrame({
    "Dept": ["HR", "HR", "IT", "IT", "Marketing", "Marketing", "Sales", "Sales"],
    "Team": ["A", "A", "B", "B", "C", "C", "D", "D"],
    "Gender": ["M", "F", "M", "F", "M", "F", "M", "F"],
    "Salary": [85, 90, 78, 85, 92, 88, 75, 80],
    "Age": [23, 25, 30, 22, 28, 26, 21, 27],
    "JoinDate": pd.to_datetime([
        "2020-01-10", "2020-02-15", "2021-03-20", "2021-04-10",
        "2020-05-30", "2020-06-25", "2021-07-15", "2021-08-01"
    ])
})

In [7]:
df

        Dept Team Gender  Salary  Age   JoinDate
0         HR    A      M      85   23 2020-01-10
1         HR    A      F      90   25 2020-02-15
2         IT    B      M      78   30 2021-03-20
3         IT    B      F      85   22 2021-04-10
4  Marketing    C      M      92   28 2020-05-30
5  Marketing    C      F      88   26 2020-06-25
6      Sales    D      M      75   21 2021-07-15
7      Sales    D      F      80   27 2021-08-01

In [8]:
df.groupby("Dept")["Salary"].mean()

Dept
HR           87.5
IT           81.5
Marketing    90.0
Sales        77.5
Name: Salary, dtype: float64

In [9]:
df.groupby("Dept")["Salary"].count()

Dept
HR           2
IT           2
Marketing    2
Sales        2
Name: Salary, dtype: int64

In [10]:
df.groupby("Dept")["Salary"].sum()

Dept
HR           175
IT           163
Marketing    180
Sales        155
Name: Salary, dtype: int64

In [11]:
df.groupby("Dept")["Salary"].min()

Dept
HR           85
IT           78
Marketing    88
Sales        75
Name: Salary, dtype: int64

In [12]:
df.groupby("Dept")["Salary"].max()

Dept
HR           90
IT           85
Marketing    92
Sales        80
Name: Salary, dtype: int64

In [13]:
df.groupby("Dept")["Salary"].agg(["mean","max","min"])

           mean  max  min
Dept
HR         87.5   90   85
IT         81.5   85   78
Marketing  90.0   92   88
Sales      77.5   80   75

In [20]:
df.groupby("Dept")["Salary"].agg(AVG="mean",Highest="max",Lowest="min")

            AVG  Highest  Lowest
Dept
HR         87.5       90      85
IT         81.5       85      78
Marketing  90.0       92      88
Sales      77.5       80      75

In [31]:
df.groupby("Team").agg({
"Salary": "mean",
"Age": "max"
})

      Salary  Age
Team
A       87.5   25
B       81.5   30
C       90.0   28
D       77.5   27

In [26]:
df["AVERAGE"] = df.groupby("Dept")["Salary"].transform("mean")

In [27]:
df

        Dept Team Gender  Salary  Age   JoinDate  AVERAGE
0         HR    A      M      85   23 2020-01-10     87.5
1         HR    A      F      90   25 2020-02-15     87.5
2         IT    B      M      78   30 2021-03-20     81.5
3         IT    B      F      85   22 2021-04-10     81.5
4  Marketing    C      M      92   28 2020-05-30     90.0
5  Marketing    C      F      88   26 2020-06-25     90.0
6      Sales    D      M      75   21 2021-07-15     77.5
7      Sales    D      F      80   27 2021-08-01     77.5

In [29]:
df.groupby("Team").filter(lambda x: x["Salary"].mean() > 85)

        Dept Team Gender  Salary  Age   JoinDate  AVERAGE
0         HR    A      M      85   23 2020-01-10     87.5
1         HR    A      F      90   25 2020-02-15     87.5
4  Marketing    C      M      92   28 2020-05-30     90.0
5  Marketing    C      F      88   26 2020-06-25     90.0

In [37]:
df1=df.groupby("Dept").agg({
    "Salary" : "max",
    "Age" : "min"
})

In [38]:
df1

           Salary  Age
Dept
HR             90   23
IT             85   22
Marketing      92   26
Sales          80   21

In [43]:
df1.rename(columns = {"Salary" : "Sal", "Age":"AGE"})

           Sal  AGE
Dept
HR          90   23
IT          85   22
Marketing   92   26
Sales       80   21